rover_joint_publisher:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50

rover_mecanum_controller:
  type: "mecanum_drive_controller/MecanumDriveController"
  front_left_wheel_joint: "front_left_wheel_to_base"
  front_right_wheel_joint: "front_right_wheel_to_base"
  back_left_wheel_joint: "rear_left_wheel_to_base"
  back_right_wheel_joint: "rear_right_wheel_to_base"
  publish_rate: 50.0

  # Ridgeback's values
  pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 0.03] # last value default is 1000.0
  twist_covariance_diagonal: [0.001, 0.001, 0.001, 1000000.0, 1000000.0, 0.03] # last value default is 1000.0
  
  # check urdf, real robot, solidworks model description
  wheel_separation_x: 0.12 # meters
  wheel_separation_y: 0.225 # meters

  wheel_separation_multiplier: 1.0 # default: 1.0
  wheel_radius_multiplier    : 1.0 # default: 1.0

  cmd_vel_timeout: 0.25 #0.25 ridgeback robot value
  base_frame_id: "base_footprint"
  enable_odom_tf: true
